"""Production contract 2.0.0 source preparation and analysis boundary."""

from importlib import import_module
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from rdam.ingest.contracts.preparation import PreparationReceipt as PreparationReceipt
    from rdam.ingest.contracts.preparation import SpeakerCoverage as SpeakerCoverage
    from rdam.ingest.contracts.preparation import TableLinearisationParameters as TableLinearisationParameters
    from rdam.ingest.contracts.source import SpeakerIdentity as SpeakerIdentity
    from rdam.ingest.capabilities import (
        describe_capabilities as describe_capabilities,
    )
    from rdam.ingest.contracts import (
        AcquisitionCompletedEvidence as AcquisitionCompletedEvidence,
        AnalysisExecutionEvidence as AnalysisExecutionEvidence,
        AnalysisSemanticEvidence as AnalysisSemanticEvidence,
        AnalysisSubstrateTransformation as AnalysisSubstrateTransformation,
        AnchorKind as AnchorKind,
        AnchorTargetKind as AnchorTargetKind,
        AnnotationRepresentation as AnnotationRepresentation,
        ArchiveMemberAnchor as ArchiveMemberAnchor,
        AssemblyCompletedEvidence as AssemblyCompletedEvidence,
        AuthorshipRole as AuthorshipRole,
        Availability as Availability,
        CacheEligibility as CacheEligibility,
        CacheEligibilityState as CacheEligibilityState,
        CacheIdentityContext as CacheIdentityContext,
        CacheStatus as CacheStatus,
        CapabilityExecution as CapabilityExecution,
        CheckClassification as CheckClassification,
        CheckOutcome as CheckOutcome,
        CompletedStageEvidence as CompletedStageEvidence,
        ComponentFileIdentity as ComponentFileIdentity,
        ComponentIdentity as ComponentIdentity,
        ComponentIdentityState as ComponentIdentityState,
        ConfidenceKind as ConfidenceKind,
        ContentClass as ContentClass,
        ContentRepresentation as ContentRepresentation,
        CoordinateBoxAnchor as CoordinateBoxAnchor,
        ContractContext as ContractContext,
        CountContext as CountContext,
        CrossReferenceRepresentation as CrossReferenceRepresentation,
        Disposition as Disposition,
        DispositionDecision as DispositionDecision,
        DispositionReason as DispositionReason,
        EndpointAnchor as EndpointAnchor,
        ErstCandidateDecision as ErstCandidateDecision,
        ErstDecision as ErstDecision,
        ErstDecodeReceipt as ErstDecodeReceipt,
        EvidenceCapability as EvidenceCapability,
        FailureCategory as FailureCategory,
        FailureExecutionEvidence as FailureExecutionEvidence,
        FidelityClass as FidelityClass,
        FormalismCapability as FormalismCapability,
        IdentifierContext as IdentifierContext,
        ImmutableComponentIdentity as ImmutableComponentIdentity,
        InferenceCompletedEvidence as InferenceCompletedEvidence,
        InferenceEvidence as InferenceEvidence,
        InventoryCompletedEvidence as InventoryCompletedEvidence,
        ItemAnchor as ItemAnchor,
        ItemRelationship as ItemRelationship,
        LabelledScore as LabelledScore,
        LifecycleStage as LifecycleStage,
        ListItemRepresentation as ListItemRepresentation,
        ListRepresentation as ListRepresentation,
        LoadedComponentReceipt as LoadedComponentReceipt,
        LocalToGlobalMapping as LocalToGlobalMapping,
        LossyInputPolicy as LossyInputPolicy,
        MappingStatus as MappingStatus,
        MarkerRefinementMode as MarkerRefinementMode,
        MediaReferenceRepresentation as MediaReferenceRepresentation,
        MetadataEntry as MetadataEntry,
        MetadataRepresentation as MetadataRepresentation,
        MissingDistributionContext as MissingDistributionContext,
        ModelIdentityState as ModelIdentityState,
        MutableComponentIdentity as MutableComponentIdentity,
        NamedCount as NamedCount,
        NoCompletedEvidence as NoCompletedEvidence,
        NormalizedDistribution as NormalizedDistribution,
        NotUsedComponentIdentity as NotUsedComponentIdentity,
        OperationCapability as OperationCapability,
        OriginClassification as OriginClassification,
        PageAnchor as PageAnchor,
        PageBoxAnchor as PageBoxAnchor,
        ParserAnalysisExecutionEvidence as ParserAnalysisExecutionEvidence,
        ParserAnalysisSemanticEvidence as ParserAnalysisSemanticEvidence,
        PreparationCompletedEvidence as PreparationCompletedEvidence,
        PrimaryStructureDecisionEvidence as PrimaryStructureDecisionEvidence,
        ProductionCapabilitiesSemantic as ProductionCapabilitiesSemantic,
        RawContractDeclaration as RawContractDeclaration,
        RecombinationReceipt as RecombinationReceipt,
        RedactedContentRepresentation as RedactedContentRepresentation,
        RefinementRecord as RefinementRecord,
        RelationInterpretation as RelationInterpretation,
        RelationInterpretationPolicy as RelationInterpretationPolicy,
        Retryability as Retryability,
        SafeCause as SafeCause,
        SafeCompletedStageEvidence as SafeCompletedStageEvidence,
        SafeDiagnosticContext as SafeDiagnosticContext,
        SafeFailureSemanticEvidence as SafeFailureSemanticEvidence,
        ScoreValue as ScoreValue,
        SegmentationDecisionEvidence as SegmentationDecisionEvidence,
        SourceAnchor as SourceAnchor,
        SourceDigestContext as SourceDigestContext,
        SourceFormCapability as SourceFormCapability,
        SourceOrigin as SourceOrigin,
        SourcePathAnchor as SourcePathAnchor,
        StitchingDecision as StitchingDecision,
        StructureRepresentation as StructureRepresentation,
        SupportingSignalEvidence as SupportingSignalEvidence,
        TableCell as TableCell,
        TableCoordinateAnchor as TableCoordinateAnchor,
        TableRepresentation as TableRepresentation,
        TextRepresentation as TextRepresentation,
        TextSpanAnchor as TextSpanAnchor,
        TokenMapping as TokenMapping,
        UnidentifiedComponentIdentity as UnidentifiedComponentIdentity,
        UnitExecutionReceipt as UnitExecutionReceipt,
        ValidationCheckReceipt as ValidationCheckReceipt,
        ValidationCompletedEvidence as ValidationCompletedEvidence,
        ValidationPolicy as ValidationPolicy,
    )
    from rdam.ingest.contracts.analysis import (
        AnalysedDocument as AnalysedDocument,
        AnalysedEdu as AnalysedEdu,
        AnalysedOutcome as AnalysedOutcome,
        AnalysedToken as AnalysedToken,
        AnalysisAnchor as AnalysisAnchor,
        AnalysisPolicy as AnalysisPolicy,
        AnalysisRequest as AnalysisRequest,
        AnalysisStatus as AnalysisStatus,
        EmptyPrimaryAnalysisOutcome as EmptyPrimaryAnalysisOutcome,
        ParserAnalysisResult as ParserAnalysisResult,
        ProductionAnalysisOutcome as ProductionAnalysisOutcome,
        ValidationReceipt as ValidationReceipt,
    )
    from rdam.ingest.contracts.base import (
        INGEST_PIPELINE_VERSION as INGEST_PIPELINE_VERSION,
        INGEST_SCHEMA_NAME as INGEST_SCHEMA_NAME,
        INGEST_SCHEMA_VERSION as INGEST_SCHEMA_VERSION,
        PRODUCTION_CONTRACT as PRODUCTION_CONTRACT,
        READABLE_CONTRACT_VERSIONS as READABLE_CONTRACT_VERSIONS,
        WRITE_CONTRACT_VERSION as WRITE_CONTRACT_VERSION,
        CoverageUnit as CoverageUnit,
        ExactCoverage as ExactCoverage,
        SemanticVersion as SemanticVersion,
        Sha256Identity as Sha256Identity,
    )
    from rdam.ingest.contracts.capabilities import (
        ProductionCapabilities as ProductionCapabilities,
    )
    from rdam.ingest.contracts.failure import (
        DiagnosticPolicy as DiagnosticPolicy,
        DiagnosticProductionFailureRecord as DiagnosticProductionFailureRecord,
        ProductionFailure as ProductionFailure,
        ProductionIngestError as ProductionIngestError,
        SafeProductionFailureRecord as SafeProductionFailureRecord,
    )
    from rdam.ingest.contracts.inference import (
        CompositeAnalysisIdentity as CompositeAnalysisIdentity,
        ErstCompletionEvidence as ErstCompletionEvidence,
        EvidenceDetailPolicy as EvidenceDetailPolicy,
        OutputFormalism as OutputFormalism,
        PrimaryInferenceEvidence as PrimaryInferenceEvidence,
    )
    from rdam.ingest.contracts.preparation import (
        ContentInventory as ContentInventory,
        ContentRequirement as ContentRequirement,
        RepresentationProjection as RepresentationProjection,
        SourceProjection as SourceProjection,
        UnmetRequirement as UnmetRequirement,
        AdapterExecutionIdentity as AdapterExecutionIdentity,
        AnalysisCapacity as AnalysisCapacity,
        AnalysisPlan as AnalysisPlan,
        AnalysisPlanStatus as AnalysisPlanStatus,
        AnalysisUnit as AnalysisUnit,
        BoundaryPreference as BoundaryPreference,
        CapacityUnit as CapacityUnit,
        LineEndingParameters as LineEndingParameters,
        PlanningPolicy as PlanningPolicy,
        PreparationExecutionEvidence as PreparationExecutionEvidence,
        PreparationOutcome as PreparationOutcome,
        PreparationPolicy as PreparationPolicy,
        PreparationSemanticEvidence as PreparationSemanticEvidence,
        PreparationWarning as PreparationWarning,
        PreparedRange as PreparedRange,
        PreparedDocument as PreparedDocument,
        PreparedSegment as PreparedSegment,
        PreserveParameters as PreserveParameters,
        RecombinationLink as RecombinationLink,
        RecombinationPlan as RecombinationPlan,
        SegmentKind as SegmentKind,
        SeparatorInsertionParameters as SeparatorInsertionParameters,
        StructuralBoundary as StructuralBoundary,
        StructureKind as StructureKind,
        TransformationParameters as TransformationParameters,
        TransformationRecord as TransformationRecord,
        UnicodeNormalizationParameters as UnicodeNormalizationParameters,
    )
    from rdam.ingest.contracts.source import (
        ContentInventoryItem as ContentInventoryItem,
        ConversionActivity as ConversionActivity,
        SourceArtifact as SourceArtifact,
        SourceContractIdentity as SourceContractIdentity,
        SourceForm as SourceForm,
        SourceSummary as SourceSummary,
    )
    from rdam.ingest.serialization import (
        PersistedContract as PersistedContract,
        UnsupportedContractKindError as UnsupportedContractKindError,
        UnsupportedContractVersionError as UnsupportedContractVersionError,
        load_contract as load_contract,
        serialize_contract as serialize_contract,
    )
    from rdam.ingest.service import (
        AnalysisIdentityProvider as AnalysisIdentityProvider,
        AnalysisParser as AnalysisParser,
        ErstCompletionParser as ErstCompletionParser,
        ProductionIngestor as ProductionIngestor,
    )

_EXPORT_MODULES: dict[str, str] = {
    "PreparationReceipt": "rdam.ingest.contracts.preparation",
    "SpeakerCoverage": "rdam.ingest.contracts.preparation",
    "TableLinearisationParameters": "rdam.ingest.contracts.preparation",
    "SpeakerIdentity": "rdam.ingest.contracts.source",
    "describe_capabilities": "rdam.ingest.capabilities",
    "AcquisitionCompletedEvidence": "rdam.ingest.contracts",
    "AnalysisExecutionEvidence": "rdam.ingest.contracts",
    "AnalysisSemanticEvidence": "rdam.ingest.contracts",
    "AnalysisSubstrateTransformation": "rdam.ingest.contracts",
    "AnchorKind": "rdam.ingest.contracts",
    "AnchorTargetKind": "rdam.ingest.contracts",
    "AnnotationRepresentation": "rdam.ingest.contracts",
    "ArchiveMemberAnchor": "rdam.ingest.contracts",
    "AssemblyCompletedEvidence": "rdam.ingest.contracts",
    "AuthorshipRole": "rdam.ingest.contracts",
    "Availability": "rdam.ingest.contracts",
    "CacheEligibility": "rdam.ingest.contracts",
    "CacheEligibilityState": "rdam.ingest.contracts",
    "CacheIdentityContext": "rdam.ingest.contracts",
    "CacheStatus": "rdam.ingest.contracts",
    "CapabilityExecution": "rdam.ingest.contracts",
    "CheckClassification": "rdam.ingest.contracts",
    "CheckOutcome": "rdam.ingest.contracts",
    "CompletedStageEvidence": "rdam.ingest.contracts",
    "ComponentFileIdentity": "rdam.ingest.contracts",
    "ComponentIdentity": "rdam.ingest.contracts",
    "ComponentIdentityState": "rdam.ingest.contracts",
    "ConfidenceKind": "rdam.ingest.contracts",
    "ContentClass": "rdam.ingest.contracts",
    "ContentRepresentation": "rdam.ingest.contracts",
    "CoordinateBoxAnchor": "rdam.ingest.contracts",
    "ContractContext": "rdam.ingest.contracts",
    "CountContext": "rdam.ingest.contracts",
    "CrossReferenceRepresentation": "rdam.ingest.contracts",
    "Disposition": "rdam.ingest.contracts",
    "DispositionDecision": "rdam.ingest.contracts",
    "DispositionReason": "rdam.ingest.contracts",
    "EndpointAnchor": "rdam.ingest.contracts",
    "ErstCandidateDecision": "rdam.ingest.contracts",
    "ErstDecision": "rdam.ingest.contracts",
    "ErstDecodeReceipt": "rdam.ingest.contracts",
    "EvidenceCapability": "rdam.ingest.contracts",
    "FailureCategory": "rdam.ingest.contracts",
    "FailureExecutionEvidence": "rdam.ingest.contracts",
    "FidelityClass": "rdam.ingest.contracts",
    "FormalismCapability": "rdam.ingest.contracts",
    "IdentifierContext": "rdam.ingest.contracts",
    "ImmutableComponentIdentity": "rdam.ingest.contracts",
    "InferenceCompletedEvidence": "rdam.ingest.contracts",
    "InferenceEvidence": "rdam.ingest.contracts",
    "InventoryCompletedEvidence": "rdam.ingest.contracts",
    "ItemAnchor": "rdam.ingest.contracts",
    "ItemRelationship": "rdam.ingest.contracts",
    "LabelledScore": "rdam.ingest.contracts",
    "LifecycleStage": "rdam.ingest.contracts",
    "ListItemRepresentation": "rdam.ingest.contracts",
    "ListRepresentation": "rdam.ingest.contracts",
    "LoadedComponentReceipt": "rdam.ingest.contracts",
    "LocalToGlobalMapping": "rdam.ingest.contracts",
    "LossyInputPolicy": "rdam.ingest.contracts",
    "MappingStatus": "rdam.ingest.contracts",
    "MarkerRefinementMode": "rdam.ingest.contracts",
    "MediaReferenceRepresentation": "rdam.ingest.contracts",
    "MetadataEntry": "rdam.ingest.contracts",
    "MetadataRepresentation": "rdam.ingest.contracts",
    "MissingDistributionContext": "rdam.ingest.contracts",
    "ModelIdentityState": "rdam.ingest.contracts",
    "MutableComponentIdentity": "rdam.ingest.contracts",
    "NamedCount": "rdam.ingest.contracts",
    "NoCompletedEvidence": "rdam.ingest.contracts",
    "NormalizedDistribution": "rdam.ingest.contracts",
    "NotUsedComponentIdentity": "rdam.ingest.contracts",
    "OperationCapability": "rdam.ingest.contracts",
    "OriginClassification": "rdam.ingest.contracts",
    "PageAnchor": "rdam.ingest.contracts",
    "PageBoxAnchor": "rdam.ingest.contracts",
    "ParserAnalysisExecutionEvidence": "rdam.ingest.contracts",
    "ParserAnalysisSemanticEvidence": "rdam.ingest.contracts",
    "PreparationCompletedEvidence": "rdam.ingest.contracts",
    "PrimaryStructureDecisionEvidence": "rdam.ingest.contracts",
    "ProductionCapabilitiesSemantic": "rdam.ingest.contracts",
    "RawContractDeclaration": "rdam.ingest.contracts",
    "RecombinationReceipt": "rdam.ingest.contracts",
    "RedactedContentRepresentation": "rdam.ingest.contracts",
    "RefinementRecord": "rdam.ingest.contracts",
    "RelationInterpretation": "rdam.ingest.contracts",
    "RelationInterpretationPolicy": "rdam.ingest.contracts",
    "Retryability": "rdam.ingest.contracts",
    "SafeCause": "rdam.ingest.contracts",
    "SafeCompletedStageEvidence": "rdam.ingest.contracts",
    "SafeDiagnosticContext": "rdam.ingest.contracts",
    "SafeFailureSemanticEvidence": "rdam.ingest.contracts",
    "ScoreValue": "rdam.ingest.contracts",
    "SegmentationDecisionEvidence": "rdam.ingest.contracts",
    "SourceAnchor": "rdam.ingest.contracts",
    "SourceDigestContext": "rdam.ingest.contracts",
    "SourceFormCapability": "rdam.ingest.contracts",
    "SourceOrigin": "rdam.ingest.contracts",
    "SourcePathAnchor": "rdam.ingest.contracts",
    "StitchingDecision": "rdam.ingest.contracts",
    "StructureRepresentation": "rdam.ingest.contracts",
    "SupportingSignalEvidence": "rdam.ingest.contracts",
    "TableCell": "rdam.ingest.contracts",
    "TableCoordinateAnchor": "rdam.ingest.contracts",
    "TableRepresentation": "rdam.ingest.contracts",
    "TextRepresentation": "rdam.ingest.contracts",
    "TextSpanAnchor": "rdam.ingest.contracts",
    "TokenMapping": "rdam.ingest.contracts",
    "UnidentifiedComponentIdentity": "rdam.ingest.contracts",
    "UnitExecutionReceipt": "rdam.ingest.contracts",
    "ValidationCheckReceipt": "rdam.ingest.contracts",
    "ValidationCompletedEvidence": "rdam.ingest.contracts",
    "ValidationPolicy": "rdam.ingest.contracts",
    "AnalysedDocument": "rdam.ingest.contracts.analysis",
    "AnalysedEdu": "rdam.ingest.contracts.analysis",
    "AnalysedOutcome": "rdam.ingest.contracts.analysis",
    "AnalysedToken": "rdam.ingest.contracts.analysis",
    "AnalysisAnchor": "rdam.ingest.contracts.analysis",
    "AnalysisPolicy": "rdam.ingest.contracts.analysis",
    "AnalysisRequest": "rdam.ingest.contracts.analysis",
    "AnalysisStatus": "rdam.ingest.contracts.analysis",
    "EmptyPrimaryAnalysisOutcome": "rdam.ingest.contracts.analysis",
    "ParserAnalysisResult": "rdam.ingest.contracts.analysis",
    "ProductionAnalysisOutcome": "rdam.ingest.contracts.analysis",
    "ValidationReceipt": "rdam.ingest.contracts.analysis",
    "INGEST_PIPELINE_VERSION": "rdam.ingest.contracts.base",
    "INGEST_SCHEMA_NAME": "rdam.ingest.contracts.base",
    "INGEST_SCHEMA_VERSION": "rdam.ingest.contracts.base",
    "PRODUCTION_CONTRACT": "rdam.ingest.contracts.base",
    "READABLE_CONTRACT_VERSIONS": "rdam.ingest.contracts.base",
    "WRITE_CONTRACT_VERSION": "rdam.ingest.contracts.base",
    "CoverageUnit": "rdam.ingest.contracts.base",
    "ExactCoverage": "rdam.ingest.contracts.base",
    "SemanticVersion": "rdam.ingest.contracts.base",
    "Sha256Identity": "rdam.ingest.contracts.base",
    "ProductionCapabilities": "rdam.ingest.contracts.capabilities",
    "DiagnosticPolicy": "rdam.ingest.contracts.failure",
    "DiagnosticProductionFailureRecord": "rdam.ingest.contracts.failure",
    "ProductionFailure": "rdam.ingest.contracts.failure",
    "ProductionIngestError": "rdam.ingest.contracts.failure",
    "SafeProductionFailureRecord": "rdam.ingest.contracts.failure",
    "CompositeAnalysisIdentity": "rdam.ingest.contracts.inference",
    "ErstCompletionEvidence": "rdam.ingest.contracts.inference",
    "EvidenceDetailPolicy": "rdam.ingest.contracts.inference",
    "OutputFormalism": "rdam.ingest.contracts.inference",
    "PrimaryInferenceEvidence": "rdam.ingest.contracts.inference",
    "ContentInventory": "rdam.ingest.contracts.preparation",
    "ContentRequirement": "rdam.ingest.contracts.preparation",
    "RepresentationProjection": "rdam.ingest.contracts.preparation",
    "SourceProjection": "rdam.ingest.contracts.preparation",
    "UnmetRequirement": "rdam.ingest.contracts.preparation",
    "AdapterExecutionIdentity": "rdam.ingest.contracts.preparation",
    "AnalysisCapacity": "rdam.ingest.contracts.preparation",
    "AnalysisPlan": "rdam.ingest.contracts.preparation",
    "AnalysisPlanStatus": "rdam.ingest.contracts.preparation",
    "AnalysisUnit": "rdam.ingest.contracts.preparation",
    "BoundaryPreference": "rdam.ingest.contracts.preparation",
    "CapacityUnit": "rdam.ingest.contracts.preparation",
    "LineEndingParameters": "rdam.ingest.contracts.preparation",
    "PlanningPolicy": "rdam.ingest.contracts.preparation",
    "PreparationExecutionEvidence": "rdam.ingest.contracts.preparation",
    "PreparationOutcome": "rdam.ingest.contracts.preparation",
    "PreparationPolicy": "rdam.ingest.contracts.preparation",
    "PreparationSemanticEvidence": "rdam.ingest.contracts.preparation",
    "PreparationWarning": "rdam.ingest.contracts.preparation",
    "PreparedRange": "rdam.ingest.contracts.preparation",
    "PreparedDocument": "rdam.ingest.contracts.preparation",
    "PreparedSegment": "rdam.ingest.contracts.preparation",
    "PreserveParameters": "rdam.ingest.contracts.preparation",
    "RecombinationLink": "rdam.ingest.contracts.preparation",
    "RecombinationPlan": "rdam.ingest.contracts.preparation",
    "SegmentKind": "rdam.ingest.contracts.preparation",
    "SeparatorInsertionParameters": "rdam.ingest.contracts.preparation",
    "StructuralBoundary": "rdam.ingest.contracts.preparation",
    "StructureKind": "rdam.ingest.contracts.preparation",
    "TransformationParameters": "rdam.ingest.contracts.preparation",
    "TransformationRecord": "rdam.ingest.contracts.preparation",
    "UnicodeNormalizationParameters": "rdam.ingest.contracts.preparation",
    "ContentInventoryItem": "rdam.ingest.contracts.source",
    "ConversionActivity": "rdam.ingest.contracts.source",
    "SourceArtifact": "rdam.ingest.contracts.source",
    "SourceContractIdentity": "rdam.ingest.contracts.source",
    "SourceForm": "rdam.ingest.contracts.source",
    "SourceSummary": "rdam.ingest.contracts.source",
    "PersistedContract": "rdam.ingest.serialization",
    "UnsupportedContractKindError": "rdam.ingest.serialization",
    "UnsupportedContractVersionError": "rdam.ingest.serialization",
    "load_contract": "rdam.ingest.serialization",
    "serialize_contract": "rdam.ingest.serialization",
    "AnalysisIdentityProvider": "rdam.ingest.service",
    "AnalysisParser": "rdam.ingest.service",
    "ErstCompletionParser": "rdam.ingest.service",
    "ProductionIngestor": "rdam.ingest.service",
}

__all__ = [
    "INGEST_PIPELINE_VERSION",
    "INGEST_SCHEMA_NAME",
    "INGEST_SCHEMA_VERSION",
    "PRODUCTION_CONTRACT",
    "READABLE_CONTRACT_VERSIONS",
    "WRITE_CONTRACT_VERSION",
    "AcquisitionCompletedEvidence",
    "AdapterExecutionIdentity",
    "AnalysedDocument",
    "AnalysedEdu",
    "AnalysedOutcome",
    "AnalysedToken",
    "AnalysisAnchor",
    "AnalysisCapacity",
    "AnalysisExecutionEvidence",
    "AnalysisIdentityProvider",
    "AnalysisParser",
    "AnalysisPlan",
    "AnalysisPlanStatus",
    "AnalysisPolicy",
    "AnalysisRequest",
    "AnalysisSemanticEvidence",
    "AnalysisStatus",
    "AnalysisSubstrateTransformation",
    "AnalysisUnit",
    "AnchorKind",
    "AnchorTargetKind",
    "AnnotationRepresentation",
    "ArchiveMemberAnchor",
    "AssemblyCompletedEvidence",
    "AuthorshipRole",
    "Availability",
    "BoundaryPreference",
    "CacheEligibility",
    "CacheEligibilityState",
    "CacheIdentityContext",
    "CacheStatus",
    "CapabilityExecution",
    "CapacityUnit",
    "CheckClassification",
    "CheckOutcome",
    "CompletedStageEvidence",
    "ComponentFileIdentity",
    "ComponentIdentity",
    "ComponentIdentityState",
    "CompositeAnalysisIdentity",
    "ConfidenceKind",
    "ContentClass",
    "ContentInventory",
    "ContentInventoryItem",
    "ContentRepresentation",
    "ContentRequirement",
    "ContractContext",
    "ConversionActivity",
    "CoordinateBoxAnchor",
    "CountContext",
    "CoverageUnit",
    "CrossReferenceRepresentation",
    "DiagnosticPolicy",
    "DiagnosticProductionFailureRecord",
    "Disposition",
    "DispositionDecision",
    "DispositionReason",
    "EmptyPrimaryAnalysisOutcome",
    "EndpointAnchor",
    "ErstCandidateDecision",
    "ErstCompletionEvidence",
    "ErstCompletionParser",
    "ErstDecision",
    "ErstDecodeReceipt",
    "EvidenceCapability",
    "EvidenceDetailPolicy",
    "ExactCoverage",
    "FailureCategory",
    "FailureExecutionEvidence",
    "FidelityClass",
    "FormalismCapability",
    "IdentifierContext",
    "ImmutableComponentIdentity",
    "InferenceCompletedEvidence",
    "InferenceEvidence",
    "InventoryCompletedEvidence",
    "ItemAnchor",
    "ItemRelationship",
    "LabelledScore",
    "LifecycleStage",
    "LineEndingParameters",
    "ListItemRepresentation",
    "ListRepresentation",
    "LoadedComponentReceipt",
    "LocalToGlobalMapping",
    "LossyInputPolicy",
    "MappingStatus",
    "MarkerRefinementMode",
    "MediaReferenceRepresentation",
    "MetadataEntry",
    "MetadataRepresentation",
    "MissingDistributionContext",
    "ModelIdentityState",
    "MutableComponentIdentity",
    "NamedCount",
    "NoCompletedEvidence",
    "NormalizedDistribution",
    "NotUsedComponentIdentity",
    "OperationCapability",
    "OriginClassification",
    "OutputFormalism",
    "PageAnchor",
    "PageBoxAnchor",
    "ParserAnalysisExecutionEvidence",
    "ParserAnalysisResult",
    "ParserAnalysisSemanticEvidence",
    "PersistedContract",
    "PlanningPolicy",
    "PreparationCompletedEvidence",
    "PreparationExecutionEvidence",
    "PreparationOutcome",
    "PreparationPolicy",
    "PreparationReceipt",
    "PreparationSemanticEvidence",
    "PreparationWarning",
    "PreparedDocument",
    "PreparedRange",
    "PreparedSegment",
    "PreserveParameters",
    "PrimaryInferenceEvidence",
    "PrimaryStructureDecisionEvidence",
    "ProductionAnalysisOutcome",
    "ProductionCapabilities",
    "ProductionCapabilitiesSemantic",
    "ProductionFailure",
    "ProductionIngestError",
    "ProductionIngestor",
    "RawContractDeclaration",
    "RecombinationLink",
    "RecombinationPlan",
    "RecombinationReceipt",
    "RedactedContentRepresentation",
    "RefinementRecord",
    "RelationInterpretation",
    "RelationInterpretationPolicy",
    "RepresentationProjection",
    "Retryability",
    "SafeCause",
    "SafeCompletedStageEvidence",
    "SafeDiagnosticContext",
    "SafeFailureSemanticEvidence",
    "SafeProductionFailureRecord",
    "ScoreValue",
    "SegmentKind",
    "SegmentationDecisionEvidence",
    "SemanticVersion",
    "SeparatorInsertionParameters",
    "Sha256Identity",
    "SourceAnchor",
    "SourceArtifact",
    "SourceContractIdentity",
    "SourceDigestContext",
    "SourceForm",
    "SourceFormCapability",
    "SourceOrigin",
    "SourcePathAnchor",
    "SourceProjection",
    "SourceSummary",
    "SpeakerCoverage",
    "SpeakerIdentity",
    "StitchingDecision",
    "StructuralBoundary",
    "StructureKind",
    "StructureRepresentation",
    "SupportingSignalEvidence",
    "TableCell",
    "TableCoordinateAnchor",
    "TableLinearisationParameters",
    "TableRepresentation",
    "TextRepresentation",
    "TextSpanAnchor",
    "TokenMapping",
    "TransformationParameters",
    "TransformationRecord",
    "UnicodeNormalizationParameters",
    "UnidentifiedComponentIdentity",
    "UnitExecutionReceipt",
    "UnmetRequirement",
    "UnsupportedContractKindError",
    "UnsupportedContractVersionError",
    "ValidationCheckReceipt",
    "ValidationCompletedEvidence",
    "ValidationPolicy",
    "ValidationReceipt",
    "describe_capabilities",
    "load_contract",
    "serialize_contract",
]


def __getattr__(name: str) -> object:
    """Resolve public contracts without loading unrelated technique implementations."""
    module = _EXPORT_MODULES.get(name)
    if module is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    value: object = getattr(import_module(module), name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(__all__))
