"""Public model namespace for production contract 2.0.0."""

from importlib import import_module
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from rdam.ingest.contracts.preparation import PreparationReceipt as PreparationReceipt
    from rdam.ingest.contracts.preparation import SpeakerCoverage as SpeakerCoverage
    from rdam.ingest.contracts.preparation import TableLinearisationParameters as TableLinearisationParameters
    from rdam.ingest.contracts.source import SpeakerIdentity as SpeakerIdentity
    from rdam.ingest.contracts.analysis import (
        AnalysedDocument as AnalysedDocument,
        AnalysedEdu as AnalysedEdu,
        AnalysedOutcome as AnalysedOutcome,
        AnalysedToken as AnalysedToken,
        AnalysisAnchor as AnalysisAnchor,
        AnalysisExecutionEvidence as AnalysisExecutionEvidence,
        AnalysisPolicy as AnalysisPolicy,
        AnalysisRequest as AnalysisRequest,
        AnalysisSemanticEvidence as AnalysisSemanticEvidence,
        AnalysisStatus as AnalysisStatus,
        AnalysisSubstrateTransformation as AnalysisSubstrateTransformation,
        AnchorTargetKind as AnchorTargetKind,
        CacheStatus as CacheStatus,
        CheckClassification as CheckClassification,
        CheckOutcome as CheckOutcome,
        EmptyPrimaryAnalysisOutcome as EmptyPrimaryAnalysisOutcome,
        EndpointAnchor as EndpointAnchor,
        FidelityClass as FidelityClass,
        LocalToGlobalMapping as LocalToGlobalMapping,
        LossyInputPolicy as LossyInputPolicy,
        MarkerRefinementMode as MarkerRefinementMode,
        ParserAnalysisExecutionEvidence as ParserAnalysisExecutionEvidence,
        ParserAnalysisResult as ParserAnalysisResult,
        ParserAnalysisSemanticEvidence as ParserAnalysisSemanticEvidence,
        ProductionAnalysisOutcome as ProductionAnalysisOutcome,
        RecombinationReceipt as RecombinationReceipt,
        RelationInterpretationPolicy as RelationInterpretationPolicy,
        StitchingDecision as StitchingDecision,
        TokenMapping as TokenMapping,
        UnitExecutionReceipt as UnitExecutionReceipt,
        ValidationCheckReceipt as ValidationCheckReceipt,
        ValidationPolicy as ValidationPolicy,
        ValidationReceipt as ValidationReceipt,
    )
    from rdam.ingest.contracts.base import (
        INGEST_PIPELINE_VERSION as INGEST_PIPELINE_VERSION,
        INGEST_SCHEMA_NAME as INGEST_SCHEMA_NAME,
        INGEST_SCHEMA_VERSION as INGEST_SCHEMA_VERSION,
        PRODUCTION_CONTRACT as PRODUCTION_CONTRACT,
        READABLE_CONTRACT_VERSIONS as READABLE_CONTRACT_VERSIONS,
        WRITE_CONTRACT_VERSION as WRITE_CONTRACT_VERSION,
        CoverageUnit as CoverageUnit,
        ExactCoverage as ExactCoverage,
        SemanticVersion as SemanticVersion,
        Sha256Identity as Sha256Identity,
        StrictContractModel as StrictContractModel,
    )
    from rdam.ingest.contracts.capabilities import (
        Availability as Availability,
        CacheEligibility as CacheEligibility,
        CacheEligibilityState as CacheEligibilityState,
        CapabilityExecution as CapabilityExecution,
        EvidenceCapability as EvidenceCapability,
        FormalismCapability as FormalismCapability,
        ModelIdentityState as ModelIdentityState,
        OperationCapability as OperationCapability,
        ProductionCapabilities as ProductionCapabilities,
        ProductionCapabilitiesSemantic as ProductionCapabilitiesSemantic,
        SourceFormCapability as SourceFormCapability,
    )
    from rdam.ingest.contracts.failure import (
        AcquisitionCompletedEvidence as AcquisitionCompletedEvidence,
        AssemblyCompletedEvidence as AssemblyCompletedEvidence,
        CacheIdentityContext as CacheIdentityContext,
        CompletedStageEvidence as CompletedStageEvidence,
        ContractContext as ContractContext,
        CountContext as CountContext,
        DiagnosticPolicy as DiagnosticPolicy,
        DiagnosticProductionFailureRecord as DiagnosticProductionFailureRecord,
        FailureCategory as FailureCategory,
        FailureExecutionEvidence as FailureExecutionEvidence,
        IdentifierContext as IdentifierContext,
        InferenceCompletedEvidence as InferenceCompletedEvidence,
        InventoryCompletedEvidence as InventoryCompletedEvidence,
        LifecycleStage as LifecycleStage,
        MissingDistributionContext as MissingDistributionContext,
        NoCompletedEvidence as NoCompletedEvidence,
        PreparationCompletedEvidence as PreparationCompletedEvidence,
        ProductionFailure as ProductionFailure,
        ProductionIngestError as ProductionIngestError,
        Retryability as Retryability,
        SafeCause as SafeCause,
        SafeCompletedStageEvidence as SafeCompletedStageEvidence,
        SafeDiagnosticContext as SafeDiagnosticContext,
        SafeFailureSemanticEvidence as SafeFailureSemanticEvidence,
        SafeProductionFailureRecord as SafeProductionFailureRecord,
        SourceDigestContext as SourceDigestContext,
        ValidationCompletedEvidence as ValidationCompletedEvidence,
    )
    from rdam.ingest.contracts.inference import (
        ComponentFileIdentity as ComponentFileIdentity,
        ComponentIdentity as ComponentIdentity,
        ComponentIdentityState as ComponentIdentityState,
        CompositeAnalysisIdentity as CompositeAnalysisIdentity,
        ConfidenceKind as ConfidenceKind,
        ErstCandidateDecision as ErstCandidateDecision,
        ErstCompletionEvidence as ErstCompletionEvidence,
        ErstDecision as ErstDecision,
        ErstDecodeReceipt as ErstDecodeReceipt,
        EvidenceDetailPolicy as EvidenceDetailPolicy,
        ImmutableComponentIdentity as ImmutableComponentIdentity,
        InferenceEvidence as InferenceEvidence,
        LabelledScore as LabelledScore,
        LoadedComponentReceipt as LoadedComponentReceipt,
        MappingStatus as MappingStatus,
        MutableComponentIdentity as MutableComponentIdentity,
        NamedCount as NamedCount,
        NormalizedDistribution as NormalizedDistribution,
        NotUsedComponentIdentity as NotUsedComponentIdentity,
        OutputFormalism as OutputFormalism,
        PrimaryInferenceEvidence as PrimaryInferenceEvidence,
        PrimaryStructureDecisionEvidence as PrimaryStructureDecisionEvidence,
        RefinementRecord as RefinementRecord,
        RelationInterpretation as RelationInterpretation,
        ScoreValue as ScoreValue,
        SegmentationDecisionEvidence as SegmentationDecisionEvidence,
        SupportingSignalEvidence as SupportingSignalEvidence,
        UnidentifiedComponentIdentity as UnidentifiedComponentIdentity,
    )
    from rdam.ingest.contracts.preparation import (
        ContentInventory as ContentInventory,
        ContentRequirement as ContentRequirement,
        RepresentationProjection as RepresentationProjection,
        SourceProjection as SourceProjection,
        UnmetRequirement as UnmetRequirement,
        AdapterExecutionIdentity as AdapterExecutionIdentity,
        AnalysisCapacity as AnalysisCapacity,
        AnalysisPlan as AnalysisPlan,
        AnalysisPlanStatus as AnalysisPlanStatus,
        AnalysisUnit as AnalysisUnit,
        BoundaryPreference as BoundaryPreference,
        CapacityUnit as CapacityUnit,
        LineEndingParameters as LineEndingParameters,
        PlanningPolicy as PlanningPolicy,
        PreparationExecutionEvidence as PreparationExecutionEvidence,
        PreparationOutcome as PreparationOutcome,
        PreparationPolicy as PreparationPolicy,
        PreparationSemanticEvidence as PreparationSemanticEvidence,
        PreparationWarning as PreparationWarning,
        PreparedRange as PreparedRange,
        PreparedDocument as PreparedDocument,
        PreparedSegment as PreparedSegment,
        PreserveParameters as PreserveParameters,
        RecombinationLink as RecombinationLink,
        RecombinationPlan as RecombinationPlan,
        SegmentKind as SegmentKind,
        SeparatorInsertionParameters as SeparatorInsertionParameters,
        StructuralBoundary as StructuralBoundary,
        StructureKind as StructureKind,
        TransformationParameters as TransformationParameters,
        TransformationRecord as TransformationRecord,
        UnicodeNormalizationParameters as UnicodeNormalizationParameters,
    )
    from rdam.ingest.contracts.source import (
        AnchorKind as AnchorKind,
        AnnotationRepresentation as AnnotationRepresentation,
        ArchiveMemberAnchor as ArchiveMemberAnchor,
        AuthorshipRole as AuthorshipRole,
        ContentClass as ContentClass,
        ContentInventoryItem as ContentInventoryItem,
        ContentRepresentation as ContentRepresentation,
        ConversionActivity as ConversionActivity,
        CoordinateBoxAnchor as CoordinateBoxAnchor,
        CrossReferenceRepresentation as CrossReferenceRepresentation,
        Disposition as Disposition,
        DispositionDecision as DispositionDecision,
        DispositionReason as DispositionReason,
        ItemAnchor as ItemAnchor,
        ItemRelationship as ItemRelationship,
        ListItemRepresentation as ListItemRepresentation,
        ListRepresentation as ListRepresentation,
        MediaReferenceRepresentation as MediaReferenceRepresentation,
        MetadataEntry as MetadataEntry,
        MetadataRepresentation as MetadataRepresentation,
        OriginClassification as OriginClassification,
        PageAnchor as PageAnchor,
        PageBoxAnchor as PageBoxAnchor,
        RawContractDeclaration as RawContractDeclaration,
        RedactedContentRepresentation as RedactedContentRepresentation,
        SourceAnchor as SourceAnchor,
        SourceArtifact as SourceArtifact,
        SourceContractIdentity as SourceContractIdentity,
        SourceForm as SourceForm,
        SourceOrigin as SourceOrigin,
        SourcePathAnchor as SourcePathAnchor,
        SourceSummary as SourceSummary,
        StructureRepresentation as StructureRepresentation,
        TableCell as TableCell,
        TableCoordinateAnchor as TableCoordinateAnchor,
        TableRepresentation as TableRepresentation,
        TextRepresentation as TextRepresentation,
        TextSpanAnchor as TextSpanAnchor,
    )

_EXPORT_MODULES: dict[str, str] = {
    "PreparationReceipt": "rdam.ingest.contracts.preparation",
    "SpeakerCoverage": "rdam.ingest.contracts.preparation",
    "TableLinearisationParameters": "rdam.ingest.contracts.preparation",
    "SpeakerIdentity": "rdam.ingest.contracts.source",
    "AnalysedDocument": "rdam.ingest.contracts.analysis",
    "AnalysedEdu": "rdam.ingest.contracts.analysis",
    "AnalysedOutcome": "rdam.ingest.contracts.analysis",
    "AnalysedToken": "rdam.ingest.contracts.analysis",
    "AnalysisAnchor": "rdam.ingest.contracts.analysis",
    "AnalysisExecutionEvidence": "rdam.ingest.contracts.analysis",
    "AnalysisPolicy": "rdam.ingest.contracts.analysis",
    "AnalysisRequest": "rdam.ingest.contracts.analysis",
    "AnalysisSemanticEvidence": "rdam.ingest.contracts.analysis",
    "AnalysisStatus": "rdam.ingest.contracts.analysis",
    "AnalysisSubstrateTransformation": "rdam.ingest.contracts.analysis",
    "AnchorTargetKind": "rdam.ingest.contracts.analysis",
    "CacheStatus": "rdam.ingest.contracts.analysis",
    "CheckClassification": "rdam.ingest.contracts.analysis",
    "CheckOutcome": "rdam.ingest.contracts.analysis",
    "EmptyPrimaryAnalysisOutcome": "rdam.ingest.contracts.analysis",
    "EndpointAnchor": "rdam.ingest.contracts.analysis",
    "FidelityClass": "rdam.ingest.contracts.analysis",
    "LocalToGlobalMapping": "rdam.ingest.contracts.analysis",
    "LossyInputPolicy": "rdam.ingest.contracts.analysis",
    "MarkerRefinementMode": "rdam.ingest.contracts.analysis",
    "ParserAnalysisExecutionEvidence": "rdam.ingest.contracts.analysis",
    "ParserAnalysisResult": "rdam.ingest.contracts.analysis",
    "ParserAnalysisSemanticEvidence": "rdam.ingest.contracts.analysis",
    "ProductionAnalysisOutcome": "rdam.ingest.contracts.analysis",
    "RecombinationReceipt": "rdam.ingest.contracts.analysis",
    "RelationInterpretationPolicy": "rdam.ingest.contracts.analysis",
    "StitchingDecision": "rdam.ingest.contracts.analysis",
    "TokenMapping": "rdam.ingest.contracts.analysis",
    "UnitExecutionReceipt": "rdam.ingest.contracts.analysis",
    "ValidationCheckReceipt": "rdam.ingest.contracts.analysis",
    "ValidationPolicy": "rdam.ingest.contracts.analysis",
    "ValidationReceipt": "rdam.ingest.contracts.analysis",
    "INGEST_PIPELINE_VERSION": "rdam.ingest.contracts.base",
    "INGEST_SCHEMA_NAME": "rdam.ingest.contracts.base",
    "INGEST_SCHEMA_VERSION": "rdam.ingest.contracts.base",
    "PRODUCTION_CONTRACT": "rdam.ingest.contracts.base",
    "READABLE_CONTRACT_VERSIONS": "rdam.ingest.contracts.base",
    "WRITE_CONTRACT_VERSION": "rdam.ingest.contracts.base",
    "CoverageUnit": "rdam.ingest.contracts.base",
    "ExactCoverage": "rdam.ingest.contracts.base",
    "SemanticVersion": "rdam.ingest.contracts.base",
    "Sha256Identity": "rdam.ingest.contracts.base",
    "StrictContractModel": "rdam.ingest.contracts.base",
    "Availability": "rdam.ingest.contracts.capabilities",
    "CacheEligibility": "rdam.ingest.contracts.capabilities",
    "CacheEligibilityState": "rdam.ingest.contracts.capabilities",
    "CapabilityExecution": "rdam.ingest.contracts.capabilities",
    "EvidenceCapability": "rdam.ingest.contracts.capabilities",
    "FormalismCapability": "rdam.ingest.contracts.capabilities",
    "ModelIdentityState": "rdam.ingest.contracts.capabilities",
    "OperationCapability": "rdam.ingest.contracts.capabilities",
    "ProductionCapabilities": "rdam.ingest.contracts.capabilities",
    "ProductionCapabilitiesSemantic": "rdam.ingest.contracts.capabilities",
    "SourceFormCapability": "rdam.ingest.contracts.capabilities",
    "AcquisitionCompletedEvidence": "rdam.ingest.contracts.failure",
    "AssemblyCompletedEvidence": "rdam.ingest.contracts.failure",
    "CacheIdentityContext": "rdam.ingest.contracts.failure",
    "CompletedStageEvidence": "rdam.ingest.contracts.failure",
    "ContractContext": "rdam.ingest.contracts.failure",
    "CountContext": "rdam.ingest.contracts.failure",
    "DiagnosticPolicy": "rdam.ingest.contracts.failure",
    "DiagnosticProductionFailureRecord": "rdam.ingest.contracts.failure",
    "FailureCategory": "rdam.ingest.contracts.failure",
    "FailureExecutionEvidence": "rdam.ingest.contracts.failure",
    "IdentifierContext": "rdam.ingest.contracts.failure",
    "InferenceCompletedEvidence": "rdam.ingest.contracts.failure",
    "InventoryCompletedEvidence": "rdam.ingest.contracts.failure",
    "LifecycleStage": "rdam.ingest.contracts.failure",
    "MissingDistributionContext": "rdam.ingest.contracts.failure",
    "NoCompletedEvidence": "rdam.ingest.contracts.failure",
    "PreparationCompletedEvidence": "rdam.ingest.contracts.failure",
    "ProductionFailure": "rdam.ingest.contracts.failure",
    "ProductionIngestError": "rdam.ingest.contracts.failure",
    "Retryability": "rdam.ingest.contracts.failure",
    "SafeCause": "rdam.ingest.contracts.failure",
    "SafeCompletedStageEvidence": "rdam.ingest.contracts.failure",
    "SafeDiagnosticContext": "rdam.ingest.contracts.failure",
    "SafeFailureSemanticEvidence": "rdam.ingest.contracts.failure",
    "SafeProductionFailureRecord": "rdam.ingest.contracts.failure",
    "SourceDigestContext": "rdam.ingest.contracts.failure",
    "ValidationCompletedEvidence": "rdam.ingest.contracts.failure",
    "ComponentFileIdentity": "rdam.ingest.contracts.inference",
    "ComponentIdentity": "rdam.ingest.contracts.inference",
    "ComponentIdentityState": "rdam.ingest.contracts.inference",
    "CompositeAnalysisIdentity": "rdam.ingest.contracts.inference",
    "ConfidenceKind": "rdam.ingest.contracts.inference",
    "ErstCandidateDecision": "rdam.ingest.contracts.inference",
    "ErstCompletionEvidence": "rdam.ingest.contracts.inference",
    "ErstDecision": "rdam.ingest.contracts.inference",
    "ErstDecodeReceipt": "rdam.ingest.contracts.inference",
    "EvidenceDetailPolicy": "rdam.ingest.contracts.inference",
    "ImmutableComponentIdentity": "rdam.ingest.contracts.inference",
    "InferenceEvidence": "rdam.ingest.contracts.inference",
    "LabelledScore": "rdam.ingest.contracts.inference",
    "LoadedComponentReceipt": "rdam.ingest.contracts.inference",
    "MappingStatus": "rdam.ingest.contracts.inference",
    "MutableComponentIdentity": "rdam.ingest.contracts.inference",
    "NamedCount": "rdam.ingest.contracts.inference",
    "NormalizedDistribution": "rdam.ingest.contracts.inference",
    "NotUsedComponentIdentity": "rdam.ingest.contracts.inference",
    "OutputFormalism": "rdam.ingest.contracts.inference",
    "PrimaryInferenceEvidence": "rdam.ingest.contracts.inference",
    "PrimaryStructureDecisionEvidence": "rdam.ingest.contracts.inference",
    "RefinementRecord": "rdam.ingest.contracts.inference",
    "RelationInterpretation": "rdam.ingest.contracts.inference",
    "ScoreValue": "rdam.ingest.contracts.inference",
    "SegmentationDecisionEvidence": "rdam.ingest.contracts.inference",
    "SupportingSignalEvidence": "rdam.ingest.contracts.inference",
    "UnidentifiedComponentIdentity": "rdam.ingest.contracts.inference",
    "ContentInventory": "rdam.ingest.contracts.preparation",
    "ContentRequirement": "rdam.ingest.contracts.preparation",
    "RepresentationProjection": "rdam.ingest.contracts.preparation",
    "SourceProjection": "rdam.ingest.contracts.preparation",
    "UnmetRequirement": "rdam.ingest.contracts.preparation",
    "AdapterExecutionIdentity": "rdam.ingest.contracts.preparation",
    "AnalysisCapacity": "rdam.ingest.contracts.preparation",
    "AnalysisPlan": "rdam.ingest.contracts.preparation",
    "AnalysisPlanStatus": "rdam.ingest.contracts.preparation",
    "AnalysisUnit": "rdam.ingest.contracts.preparation",
    "BoundaryPreference": "rdam.ingest.contracts.preparation",
    "CapacityUnit": "rdam.ingest.contracts.preparation",
    "LineEndingParameters": "rdam.ingest.contracts.preparation",
    "PlanningPolicy": "rdam.ingest.contracts.preparation",
    "PreparationExecutionEvidence": "rdam.ingest.contracts.preparation",
    "PreparationOutcome": "rdam.ingest.contracts.preparation",
    "PreparationPolicy": "rdam.ingest.contracts.preparation",
    "PreparationSemanticEvidence": "rdam.ingest.contracts.preparation",
    "PreparationWarning": "rdam.ingest.contracts.preparation",
    "PreparedRange": "rdam.ingest.contracts.preparation",
    "PreparedDocument": "rdam.ingest.contracts.preparation",
    "PreparedSegment": "rdam.ingest.contracts.preparation",
    "PreserveParameters": "rdam.ingest.contracts.preparation",
    "RecombinationLink": "rdam.ingest.contracts.preparation",
    "RecombinationPlan": "rdam.ingest.contracts.preparation",
    "SegmentKind": "rdam.ingest.contracts.preparation",
    "SeparatorInsertionParameters": "rdam.ingest.contracts.preparation",
    "StructuralBoundary": "rdam.ingest.contracts.preparation",
    "StructureKind": "rdam.ingest.contracts.preparation",
    "TransformationParameters": "rdam.ingest.contracts.preparation",
    "TransformationRecord": "rdam.ingest.contracts.preparation",
    "UnicodeNormalizationParameters": "rdam.ingest.contracts.preparation",
    "AnchorKind": "rdam.ingest.contracts.source",
    "AnnotationRepresentation": "rdam.ingest.contracts.source",
    "ArchiveMemberAnchor": "rdam.ingest.contracts.source",
    "AuthorshipRole": "rdam.ingest.contracts.source",
    "ContentClass": "rdam.ingest.contracts.source",
    "ContentInventoryItem": "rdam.ingest.contracts.source",
    "ContentRepresentation": "rdam.ingest.contracts.source",
    "ConversionActivity": "rdam.ingest.contracts.source",
    "CoordinateBoxAnchor": "rdam.ingest.contracts.source",
    "CrossReferenceRepresentation": "rdam.ingest.contracts.source",
    "Disposition": "rdam.ingest.contracts.source",
    "DispositionDecision": "rdam.ingest.contracts.source",
    "DispositionReason": "rdam.ingest.contracts.source",
    "ItemAnchor": "rdam.ingest.contracts.source",
    "ItemRelationship": "rdam.ingest.contracts.source",
    "ListItemRepresentation": "rdam.ingest.contracts.source",
    "ListRepresentation": "rdam.ingest.contracts.source",
    "MediaReferenceRepresentation": "rdam.ingest.contracts.source",
    "MetadataEntry": "rdam.ingest.contracts.source",
    "MetadataRepresentation": "rdam.ingest.contracts.source",
    "OriginClassification": "rdam.ingest.contracts.source",
    "PageAnchor": "rdam.ingest.contracts.source",
    "PageBoxAnchor": "rdam.ingest.contracts.source",
    "RawContractDeclaration": "rdam.ingest.contracts.source",
    "RedactedContentRepresentation": "rdam.ingest.contracts.source",
    "SourceAnchor": "rdam.ingest.contracts.source",
    "SourceArtifact": "rdam.ingest.contracts.source",
    "SourceContractIdentity": "rdam.ingest.contracts.source",
    "SourceForm": "rdam.ingest.contracts.source",
    "SourceOrigin": "rdam.ingest.contracts.source",
    "SourcePathAnchor": "rdam.ingest.contracts.source",
    "SourceSummary": "rdam.ingest.contracts.source",
    "StructureRepresentation": "rdam.ingest.contracts.source",
    "TableCell": "rdam.ingest.contracts.source",
    "TableCoordinateAnchor": "rdam.ingest.contracts.source",
    "TableRepresentation": "rdam.ingest.contracts.source",
    "TextRepresentation": "rdam.ingest.contracts.source",
    "TextSpanAnchor": "rdam.ingest.contracts.source",
}

__all__ = [
    "PreparationReceipt",
    "SpeakerCoverage",
    "TableLinearisationParameters",
    "SpeakerIdentity",
    "AnalysedDocument",
    "AnalysedEdu",
    "AnalysedOutcome",
    "AnalysedToken",
    "AnalysisAnchor",
    "AnalysisExecutionEvidence",
    "AnalysisPolicy",
    "AnalysisRequest",
    "AnalysisSemanticEvidence",
    "AnalysisStatus",
    "AnalysisSubstrateTransformation",
    "AnchorTargetKind",
    "CacheStatus",
    "CheckClassification",
    "CheckOutcome",
    "EmptyPrimaryAnalysisOutcome",
    "EndpointAnchor",
    "FidelityClass",
    "LocalToGlobalMapping",
    "LossyInputPolicy",
    "MarkerRefinementMode",
    "ParserAnalysisExecutionEvidence",
    "ParserAnalysisResult",
    "ParserAnalysisSemanticEvidence",
    "ProductionAnalysisOutcome",
    "RecombinationReceipt",
    "RelationInterpretationPolicy",
    "StitchingDecision",
    "TokenMapping",
    "UnitExecutionReceipt",
    "ValidationCheckReceipt",
    "ValidationPolicy",
    "ValidationReceipt",
    "INGEST_PIPELINE_VERSION",
    "INGEST_SCHEMA_NAME",
    "INGEST_SCHEMA_VERSION",
    "PRODUCTION_CONTRACT",
    "READABLE_CONTRACT_VERSIONS",
    "WRITE_CONTRACT_VERSION",
    "CoverageUnit",
    "ExactCoverage",
    "SemanticVersion",
    "Sha256Identity",
    "StrictContractModel",
    "Availability",
    "CacheEligibility",
    "CacheEligibilityState",
    "CapabilityExecution",
    "EvidenceCapability",
    "FormalismCapability",
    "ModelIdentityState",
    "OperationCapability",
    "ProductionCapabilities",
    "ProductionCapabilitiesSemantic",
    "SourceFormCapability",
    "AcquisitionCompletedEvidence",
    "AssemblyCompletedEvidence",
    "CacheIdentityContext",
    "CompletedStageEvidence",
    "ContractContext",
    "CountContext",
    "DiagnosticPolicy",
    "DiagnosticProductionFailureRecord",
    "FailureCategory",
    "FailureExecutionEvidence",
    "IdentifierContext",
    "InferenceCompletedEvidence",
    "InventoryCompletedEvidence",
    "LifecycleStage",
    "MissingDistributionContext",
    "NoCompletedEvidence",
    "PreparationCompletedEvidence",
    "ProductionFailure",
    "ProductionIngestError",
    "Retryability",
    "SafeCause",
    "SafeCompletedStageEvidence",
    "SafeDiagnosticContext",
    "SafeFailureSemanticEvidence",
    "SafeProductionFailureRecord",
    "SourceDigestContext",
    "ValidationCompletedEvidence",
    "ComponentFileIdentity",
    "ComponentIdentity",
    "ComponentIdentityState",
    "CompositeAnalysisIdentity",
    "ConfidenceKind",
    "ErstCandidateDecision",
    "ErstCompletionEvidence",
    "ErstDecision",
    "ErstDecodeReceipt",
    "EvidenceDetailPolicy",
    "ImmutableComponentIdentity",
    "InferenceEvidence",
    "LabelledScore",
    "LoadedComponentReceipt",
    "MappingStatus",
    "MutableComponentIdentity",
    "NamedCount",
    "NormalizedDistribution",
    "NotUsedComponentIdentity",
    "OutputFormalism",
    "PrimaryInferenceEvidence",
    "PrimaryStructureDecisionEvidence",
    "RefinementRecord",
    "RelationInterpretation",
    "ScoreValue",
    "SegmentationDecisionEvidence",
    "SupportingSignalEvidence",
    "UnidentifiedComponentIdentity",
    "ContentInventory",
    "ContentRequirement",
    "RepresentationProjection",
    "SourceProjection",
    "UnmetRequirement",
    "AdapterExecutionIdentity",
    "AnalysisCapacity",
    "AnalysisPlan",
    "AnalysisPlanStatus",
    "AnalysisUnit",
    "BoundaryPreference",
    "CapacityUnit",
    "LineEndingParameters",
    "PlanningPolicy",
    "PreparationExecutionEvidence",
    "PreparationOutcome",
    "PreparationPolicy",
    "PreparationSemanticEvidence",
    "PreparationWarning",
    "PreparedRange",
    "PreparedDocument",
    "PreparedSegment",
    "PreserveParameters",
    "RecombinationLink",
    "RecombinationPlan",
    "SegmentKind",
    "SeparatorInsertionParameters",
    "StructuralBoundary",
    "StructureKind",
    "TransformationParameters",
    "TransformationRecord",
    "UnicodeNormalizationParameters",
    "AnchorKind",
    "AnnotationRepresentation",
    "ArchiveMemberAnchor",
    "AuthorshipRole",
    "ContentClass",
    "ContentInventoryItem",
    "ContentRepresentation",
    "ConversionActivity",
    "CoordinateBoxAnchor",
    "CrossReferenceRepresentation",
    "Disposition",
    "DispositionDecision",
    "DispositionReason",
    "ItemAnchor",
    "ItemRelationship",
    "ListItemRepresentation",
    "ListRepresentation",
    "MediaReferenceRepresentation",
    "MetadataEntry",
    "MetadataRepresentation",
    "OriginClassification",
    "PageAnchor",
    "PageBoxAnchor",
    "RawContractDeclaration",
    "RedactedContentRepresentation",
    "SourceAnchor",
    "SourceArtifact",
    "SourceContractIdentity",
    "SourceForm",
    "SourceOrigin",
    "SourcePathAnchor",
    "SourceSummary",
    "StructureRepresentation",
    "TableCell",
    "TableCoordinateAnchor",
    "TableRepresentation",
    "TextRepresentation",
    "TextSpanAnchor",
]


def __getattr__(name: str) -> object:
    """Resolve public contracts without loading unrelated technique implementations."""
    module = _EXPORT_MODULES.get(name)
    if module is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    value: object = getattr(import_module(module), name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(__all__))
