"""rdam — the Rhetorical Discourse Analysis Machine's aggregate analysis contract.

A permanently analysis-only machine that runs several discourse and argumentation
techniques natively, side by side, without collapsing them into a common formalism.
Authority: ``specs/006-rhetorical-discourse-machine/``.
"""

from importlib.metadata import PackageNotFoundError, version

from rdam._strict import SemanticVersion, Sha256Identity, StrictModel, canonical_json_bytes, semantic_sha256
from rdam.contracts import (
    AggregateAnalysis,
    AggregateRequest,
    AvailableCapability,
    CapabilityState,
    FailedOutcome,
    FormalismChoice,
    FormalismDeclaration,
    MachineCapabilities,
    NativeTechniqueResult,
    Outcome,
    ProviderDeclaration,
    ProviderDependencyReference,
    ProviderError,
    ProviderFailure,
    ProviderProvenance,
    ProviderRequest,
    ResultOutcome,
    Retryability,
    SourceIdentity,
    StructuredInput,
    TechniqueCapability,
    UnavailableCapability,
    UnavailableOutcome,
    UnavailableReason,
    UpstreamResultReference,
    outcome_technique,
)
from rdam.frameworks import (
    BOUNDARY_TECHNIQUES,
    FRAMEWORK_SCHEME,
    STRUCTURED_INPUT_TECHNIQUES,
    FrameworkIdentity,
    FrameworkResolutionError,
    Technique,
    framework_identities,
    technique_curie,
)
from rdam.machine import Machine, Provider
from rdam.promotion import (
    BaselineComparison,
    CalibrationEvidence,
    CandidateComparison,
    CandidateIdentity,
    CompatibilityEvidence,
    EmpiricalQualityEvidence,
    EvidenceClass,
    EvidenceVerdict,
    FormalQualityEvidence,
    LatencyEvidence,
    LicensingEvidence,
    Measurement,
    PromotionDecision,
    PromotionOutcome,
    ProvenanceEvidence,
    Recommendation,
    UnmeasuredQuality,
    compare_candidates,
    load_decision,
    load_published_decision,
    serialize_decision,
    sidecar_path,
)
from rdam.serialization import PersistedRecord, UnsupportedRecordError, load, serialize

try:
    __version__ = version("rdam")
except PackageNotFoundError:
    __version__ = "unknown"

__all__ = [
    "BOUNDARY_TECHNIQUES",
    "FRAMEWORK_SCHEME",
    "STRUCTURED_INPUT_TECHNIQUES",
    "AggregateAnalysis",
    "AggregateRequest",
    "AvailableCapability",
    "BaselineComparison",
    "CalibrationEvidence",
    "CandidateComparison",
    "CandidateIdentity",
    "CapabilityState",
    "CompatibilityEvidence",
    "EmpiricalQualityEvidence",
    "EvidenceClass",
    "EvidenceVerdict",
    "FailedOutcome",
    "FormalQualityEvidence",
    "FormalismChoice",
    "FormalismDeclaration",
    "FrameworkIdentity",
    "FrameworkResolutionError",
    "LatencyEvidence",
    "LicensingEvidence",
    "Machine",
    "MachineCapabilities",
    "Measurement",
    "NativeTechniqueResult",
    "Outcome",
    "PersistedRecord",
    "PromotionDecision",
    "PromotionOutcome",
    "ProvenanceEvidence",
    "Provider",
    "ProviderDeclaration",
    "ProviderDependencyReference",
    "ProviderError",
    "ProviderFailure",
    "ProviderProvenance",
    "ProviderRequest",
    "Recommendation",
    "ResultOutcome",
    "Retryability",
    "SemanticVersion",
    "Sha256Identity",
    "SourceIdentity",
    "StrictModel",
    "StructuredInput",
    "Technique",
    "TechniqueCapability",
    "UnavailableCapability",
    "UnavailableOutcome",
    "UnavailableReason",
    "UnmeasuredQuality",
    "UnsupportedRecordError",
    "UpstreamResultReference",
    "__version__",
    "canonical_json_bytes",
    "compare_candidates",
    "framework_identities",
    "load",
    "load_decision",
    "load_published_decision",
    "outcome_technique",
    "semantic_sha256",
    "serialize",
    "serialize_decision",
    "sidecar_path",
    "technique_curie",
]
