"""Canonical production source-ingest contracts and service."""

from isanlp_rst.ingest.contracts import (
    INGEST_SCHEMA_NAME,
    INGEST_SCHEMA_VERSION,
    AnalysisAnchor,
    AnalysisStatus,
    AnalysisUnit,
    AnchorKind,
    AuthorshipRole,
    CacheStatus,
    ContentClass,
    ContentInventoryItem,
    ConversionActivity,
    Disposition,
    DispositionKind,
    DuplicateFinding,
    ExecutionReceipt,
    FailureStage,
    NativeAnchor,
    PreparationPolicy,
    PreparationReceipt,
    PreparedRange,
    PreparedRstDocument,
    PreparedSegment,
    ProductionAnalysisResult,
    ProductionIngestError,
    RawContractDeclaration,
    SegmentKind,
    SourceArtifact,
    SourceContractIdentity,
    SourceForm,
    SourceSummary,
    StructureKind,
    StructureNode,
    SubdivisionPlan,
)
from isanlp_rst.ingest.policy import AUTHORED_PROSE_V1
from isanlp_rst.ingest.service import ProductionIngestor, analyse_source

__all__ = [
    "INGEST_SCHEMA_NAME",
    "INGEST_SCHEMA_VERSION",
    "AUTHORED_PROSE_V1",
    "AnalysisAnchor",
    "AnalysisStatus",
    "AnalysisUnit",
    "AnchorKind",
    "AuthorshipRole",
    "CacheStatus",
    "ContentClass",
    "ContentInventoryItem",
    "ConversionActivity",
    "Disposition",
    "DispositionKind",
    "DuplicateFinding",
    "ExecutionReceipt",
    "FailureStage",
    "NativeAnchor",
    "PreparationPolicy",
    "PreparationReceipt",
    "PreparedRange",
    "PreparedRstDocument",
    "PreparedSegment",
    "ProductionAnalysisResult",
    "ProductionIngestor",
    "ProductionIngestError",
    "RawContractDeclaration",
    "SegmentKind",
    "SourceArtifact",
    "SourceContractIdentity",
    "SourceForm",
    "SourceSummary",
    "StructureKind",
    "StructureNode",
    "SubdivisionPlan",
    "analyse_source",
]
